config/routes.rb
Rails.application.routes.draw do
  resources :words
  resources :stories

  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users do
        collection do
          post 'login', to: 'users#login'
        end
      end
      resources :stories
      resources :words
    end
  end
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_many :words

  def as_json(*args)
    {
      :id => self.id,
      :title => self.title,
      :actual_phrases_count => self.words.length,
      :phrases_limit => self.phrases_limit,
      :words_per_phrase_limit => self.words_per_phrase_limit,
      :author => self.user,
      :words => self.words,
      :created_at => self.created_at,
      :updated_at => self.updated_at
    }
  end
end

app/controllers/api/v1/stories_controller.rb
class Api::V1::StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
    render json: @stories
    # transformed = @stories.map { |story|
    #   story[:user] = User.find(story[:user_id])
    # }
    # render json: transformed
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    render json: @story
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    user_id = story_params[:user_id]
    begin
      user = User.find(user_id)
    rescue
      return render json: {
        :success => 0,
        :message => user_id.is_a? Integer ? "User with id #{user_id} not found." : "You must login before creating a story"
      }
    end

    return render json: {
      :success => 0,
      :message => "Stories can't contains less than 6 words."
    } if story_params[:phrases_limit].to_i < 6

    return render json: {
      :success => 0,
      :message => "Stories must allow at least 1 word per phrase."
    } if story_params[:words_per_phrase_limit].to_i < 1

    @story = Story.new(story_params)

    if @story.save
      render json: {
        :success => 1,
        :data    => {
          :story => @story
        }
      }
    else
      render json: {
        :success => 0,
        :message => "Story creation FAILED."
      }
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    render json: {
      :success => 1,
      :data    => {
        :story => @story
      }
    }
    # respond_to do |format|
    #   format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      # params.require(:story).permit(:title, :words_count, :user_id)
      params.permit(:title, :phrases_limit, :words_per_phrase_limit, :user_id)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :story_title %>
  </div>

  <div class="field">
    <%= form.label :words_count %>
    <%= form.number_field :words_count, id: :story_words_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Words count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.words_count %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Words count:</strong>
  <%= @story.words_count %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>