config/routes.rb
Rails.application.routes.draw do
  resources :words
  resources :stories

  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users do
        collection do
          post 'login', to: 'users#login'
        end
      end
      resources :stories
      resources :words
    end
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :story
  belongs_to :user #, :foreign_key => :story

  def as_json(*args)
    {
      :text => self.text,
      :index => self.index,
      :created_at => self.created_at,
      :updated_at => self.updated_at,
      :story_id => self.story.id,
      :author_id => self.user.id
      # :author => User.find(self.user_id),
      # :story => Story.find(self.story_id)
      # :author => self.user,
      # :story => self.story
    }
  end
end

app/controllers/api/v1/words_controller.rb
class Api::V1::WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
    render json: @words
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    user_id = word_params[:user_id]
    begin
      @user = User.find(user_id)
    rescue
      return render json: {
        :success => 0,
        :message => "User with id '#{user_id}' doesn't exists."
      }
    end

    story_id = word_params[:story_id]
    begin
      @story = Story.find(story_id)
    rescue
      return render json: {
        :success => 0,
        :message => "Story with id '#{story_id}' doesn't exists."
      }
    end

    return render json: {
      :success => 0,
      :message => "You can't write two phrases in sequence."
    } if  not @story.words.empty? and @story.words.last.user.id == user_id

    return render json: {
      :success => 0,
      :message => "Phrase contains too much word. Max: #{words_per_phrase_limit}"
    } if word_params[:text].split.length > @story.words_per_phrase_limit

    return render json: {
      :success => 0,
      :message => "Story reached its maximum number of words."
    } unless @story.words.length < @story.phrases_limit

    params = word_params.clone
    params[:user] = @user
    params[:story] = @story
    params[:index] = @story.words.length + 1
    @word = Word.new(params)

    if @word.save
      render json: {
        :success => 1,
        :data => {
          :word => @word
        }
      }
    else
      render json: {
        :success => 0,
        :message => "Word creation FAILED."
      }
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    render json: {
      :success => 1,
      :data    => {
        :word => @word
      }
    }
    # respond_to do |format|
    #   format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      # params.require(:word).permit(:text, :index, :user_id, :story_id)
      params.permit(:text, :user_id, :story_id)
    end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, id: :word_text %>
  </div>

  <div class="field">
    <%= form.label :index %>
    <%= form.number_field :index, id: :word_index %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Index</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.text %></td>
        <td><%= word.index %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @word.text %>
</p>

<p>
  <strong>Index:</strong>
  <%= @word.index %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>